#/bin/bash
set -eux

# Don't run this script as root
[ ! "$UID" -eq 0 ] || { echo "This script must be run not be run as root."; exit 1;}

dconf write /org/gnome/shell/disable-extension-version-validation "true" #yolo
dconf write /org/gnome/shell/disable-user-extensions "false"

gnome-extensions enable Move_Clock@rmy.pobox.com
gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
gnome-extensions disable background-logo@fedorahosted.org
gnome-extensions enable dash-to-dock@micxgx.gmail.com
gnome-extensions enable gsconnect@andyholmes.github.io
gnome-extensions enable sound-output-device-chooser@kgshank.net

dconf write /org/gnome/shell/favorite-apps "['org.mozilla.firefox.desktop', 'com.getmailspring.Mailspring.desktop', 'org.gnome.Nautilus.desktop', 'com.visualstudio.code.desktop', 'com.spotify.Client', 'org.signal.Signal.desktop', 'org.standardnotes.standardnotes.desktop', 'org.gnome.Software.desktop', 'org.gnome.Terminal.desktop']"

#dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command "gnome-terminal"
#dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding "'<Primary><Alt>T'"
#dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name "'gnome-terminal'"

dconf write /org/gnome/desktop/app-folders/folder-children "@as []"
dconf write /org/gnome/desktop/background/draw-background "true"
dconf write /org/gnome/desktop/background/show-desktop-icons "true"
dconf write /org/gnome/desktop/calendar/show-weekdate "false"
dconf write /org/gnome/desktop/datetime/automatic-timezone "false"
dconf write /org/gnome/desktop/interface/automatic-mnemonics "true"
dconf write /org/gnome/desktop/interface/avatar-directories "@as []"
dconf write /org/gnome/desktop/interface/buttons-have-icons "false"
dconf write /org/gnome/desktop/interface/can-change-accels "false"
dconf write /org/gnome/desktop/interface/clock-format "'24h'"
dconf write /org/gnome/desktop/interface/clock-show-date "true"
dconf write /org/gnome/desktop/interface/clock-show-seconds "false"
dconf write /org/gnome/desktop/interface/clock-show-weekday "false"
dconf write /org/gnome/desktop/interface/cursor-blink "true"
dconf write /org/gnome/desktop/interface/cursor-blink-time "1200"
dconf write /org/gnome/desktop/interface/cursor-blink-timeout "10"
dconf write /org/gnome/desktop/interface/cursor-size "24"
dconf write /org/gnome/desktop/interface/document-font-name "'Sans 11'"
dconf write /org/gnome/desktop/interface/enable-animations "true"
dconf write /org/gnome/desktop/interface/enable-hot-corners "false"
dconf write /org/gnome/desktop/interface/gtk-color-scheme "''"
dconf write /org/gnome/desktop/interface/gtk-enable-primary-paste "true"
dconf write /org/gnome/desktop/interface/gtk-im-module "'gtk-im-context-simple'"
dconf write /org/gnome/desktop/interface/gtk-im-preedit-style "'callback'"
dconf write /org/gnome/desktop/interface/gtk-im-status-style "'callback'"
dconf write /org/gnome/desktop/interface/gtk-key-theme "'Default'"
dconf write /org/gnome/desktop/interface/gtk-timeout-initial "200"
dconf write /org/gnome/desktop/interface/gtk-timeout-repeat "20"
dconf write /org/gnome/desktop/interface/locate-pointer "false"
dconf write /org/gnome/desktop/interface/menubar-accel "'F10'"
dconf write /org/gnome/desktop/interface/menubar-detachable "false"
dconf write /org/gnome/desktop/interface/menus-have-icons "false"
dconf write /org/gnome/desktop/interface/menus-have-tearoff "false"
dconf write /org/gnome/desktop/interface/overlay-scrolling "true"
dconf write /org/gnome/desktop/interface/scaling-factor "uint32 0"
dconf write /org/gnome/desktop/interface/show-battery-percentage "false"
dconf write /org/gnome/desktop/interface/show-input-method-menu "true"
dconf write /org/gnome/desktop/interface/show-unicode-menu "true"
dconf write /org/gnome/desktop/interface/text-scaling-factor "1.0"
dconf write /org/gnome/desktop/interface/toolbar-detachable "false"
dconf write /org/gnome/desktop/interface/toolbar-icons-size "'large'"
dconf write /org/gnome/desktop/interface/toolbar-style "'both-horiz'"
dconf write /org/gnome/desktop/interface/toolkit-accessibility "false"
dconf write /org/gnome/desktop/media-handling/automount "true"
dconf write /org/gnome/desktop/media-handling/automount-open "true"
dconf write /org/gnome/desktop/media-handling/autorun-never "false"
dconf write /org/gnome/desktop/media-handling/autorun-x-content-ignore "@as []"
dconf write /org/gnome/desktop/media-handling/autorun-x-content-open-folder "@as []"
dconf write /org/gnome/desktop/media-handling/autorun-x-content-start-app "['x-content/unix-software', 'x-content/ostree-repository']"
dconf write /org/gnome/desktop/notifications/application-children "@as []"
dconf write /org/gnome/desktop/notifications/show-banners "true"
dconf write /org/gnome/desktop/notifications/show-in-lock-screen "true"
dconf write /org/gnome/desktop/peripherals/keyboard/delay "uint32 500"
dconf write /org/gnome/desktop/peripherals/keyboard/numlock-state "false"
dconf write /org/gnome/desktop/peripherals/keyboard/remember-numlock-state "true"
dconf write /org/gnome/desktop/peripherals/keyboard/repeat "true"
dconf write /org/gnome/desktop/peripherals/keyboard/repeat-interval "uint32 30"
dconf write /org/gnome/desktop/peripherals/mouse/accel-profile "'default'"
dconf write /org/gnome/desktop/peripherals/mouse/left-handed "false"
dconf write /org/gnome/desktop/peripherals/mouse/middle-click-emulation "false"
dconf write /org/gnome/desktop/peripherals/mouse/natural-scroll "false"
dconf write /org/gnome/desktop/peripherals/mouse/speed "0.0"
dconf write /org/gnome/desktop/peripherals/tablet/area "[0.0, 0.0, 0.0, 0.0]"
dconf write /org/gnome/desktop/peripherals/tablet/display "['', '', '']"
dconf write /org/gnome/desktop/peripherals/tablet/keep-aspect "false"
dconf write /org/gnome/desktop/peripherals/tablet/left-handed "false"
dconf write /org/gnome/desktop/peripherals/tablet/mapping "'absolute'"
dconf write /org/gnome/desktop/peripherals/tablet/output "['', '', '']"
dconf write /org/gnome/desktop/peripherals/touchscreen/display "['', '', '']"
dconf write /org/gnome/desktop/peripherals/touchscreen/output "['', '', '']"
dconf write /org/gnome/desktop/peripherals/trackball/accel-profile "'default'"
dconf write /org/gnome/desktop/peripherals/trackball/middle-click-emulation "false"
dconf write /org/gnome/desktop/peripherals/trackball/scroll-wheel-emulation-button "0"
dconf write /org/gnome/desktop/privacy/disable-camera "false"
dconf write /org/gnome/desktop/privacy/disable-microphone "false"
dconf write /org/gnome/desktop/privacy/disable-sound-output "false"
dconf write /org/gnome/desktop/privacy/hide-identity "false"
dconf write /org/gnome/desktop/privacy/old-files-age "uint32 30"
dconf write /org/gnome/desktop/privacy/recent-files-max-age "-1"
dconf write /org/gnome/desktop/privacy/remember-app-usage "true"
dconf write /org/gnome/desktop/privacy/remember-recent-files "true"
dconf write /org/gnome/desktop/privacy/remove-old-temp-files "false"
dconf write /org/gnome/desktop/privacy/remove-old-trash-files "false"
dconf write /org/gnome/desktop/privacy/report-technical-problems "true"
dconf write /org/gnome/desktop/privacy/send-software-usage-stats "false"
dconf write /org/gnome/desktop/privacy/show-full-name-in-top-bar "true"
dconf write /org/gnome/desktop/privacy/usb-protection "true"
dconf write /org/gnome/desktop/privacy/usb-protection-level "'lockscreen'"
dconf write /org/gnome/desktop/screensaver/color-shading-type "'solid'"
dconf write /org/gnome/desktop/screensaver/embedded-keyboard-command "''"
dconf write /org/gnome/desktop/screensaver/embedded-keyboard-enabled "false"
dconf write /org/gnome/desktop/screensaver/idle-activation-enabled "true"
dconf write /org/gnome/desktop/screensaver/lock-delay "uint32 0"
dconf write /org/gnome/desktop/screensaver/lock-enabled "true"
dconf write /org/gnome/desktop/screensaver/logout-command "''"
dconf write /org/gnome/desktop/screensaver/logout-delay "uint32 7200"
dconf write /org/gnome/desktop/screensaver/logout-enabled "false"
dconf write /org/gnome/desktop/screensaver/picture-opacity "100"
dconf write /org/gnome/desktop/screensaver/picture-options "'zoom'"
dconf write /org/gnome/desktop/screensaver/primary-color "'#023c88'"
dconf write /org/gnome/desktop/screensaver/secondary-color "'#5789ca'"
dconf write /org/gnome/desktop/screensaver/show-full-name-in-top-bar "true"
dconf write /org/gnome/desktop/screensaver/show-notifications "false"
dconf write /org/gnome/desktop/screensaver/status-message-enabled "true"
dconf write /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend "true"
dconf write /org/gnome/desktop/screensaver/user-switch-enabled "true"
dconf write /org/gnome/desktop/sound/allow-volume-above-100-percent "false"
dconf write /org/gnome/desktop/sound/event-sounds "true"
dconf write /org/gnome/desktop/sound/input-feedback-sounds "true"
dconf write /org/gnome/desktop/thumbnail-cache/maximum-age "180"
dconf write /org/gnome/desktop/thumbnail-cache/maximum-size "512"
dconf write /org/gnome/desktop/thumbnailers/disable "@as []"
dconf write /org/gnome/desktop/thumbnailers/disable-all "false"
dconf write /org/gnome/desktop/wm/keybindings/activate-window-menu "['<Alt>space']"
dconf write /org/gnome/desktop/wm/keybindings/always-on-top "@as []"
dconf write /org/gnome/desktop/wm/keybindings/begin-move "['<Alt>F7']"
dconf write /org/gnome/desktop/wm/keybindings/begin-resize "['<Alt>F8']"
dconf write /org/gnome/desktop/wm/keybindings/close "['<Alt>F4']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-group "['<Alt>F6']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-group-backward "['<Shift><Alt>F6']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-panels "['<Control><Alt>Escape']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-panels-backward "['<Shift><Control><Alt>Escape']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-windows "['<Alt>Escape']"
dconf write /org/gnome/desktop/wm/keybindings/cycle-windows-backward "['<Shift><Alt>Escape']"
dconf write /org/gnome/desktop/wm/keybindings/lower "@as []"
dconf write /org/gnome/desktop/wm/keybindings/maximize "['<Super>Up']"
dconf write /org/gnome/desktop/wm/keybindings/maximize-horizontally "@as []"
dconf write /org/gnome/desktop/wm/keybindings/maximize-vertically "@as []"
dconf write /org/gnome/desktop/wm/keybindings/minimize "['<Super>h']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-center "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-corner-ne "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-corner-nw "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-corner-se "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-corner-sw "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-down "['<Super><Shift>Down']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-left "['<Super><Shift>Left']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-right "['<Super><Shift>Right']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-monitor-up "['<Super><Shift>Up']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-side-e "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-side-n "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-side-s "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-side-w "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-1 "['<Super><Shift>Home']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-10 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-11 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-12 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-2 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-3 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-4 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-5 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-6 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-7 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-8 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-9 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-down "['<Super><Shift>Page_Down', '<Control><Shift><Alt>Down']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-last "['<Super><Shift>End']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-left "['<Control><Shift><Alt>Left']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-right "['<Control><Shift><Alt>Right']"
dconf write /org/gnome/desktop/wm/keybindings/move-to-workspace-up "['<Super><Shift>Page_Up', '<Control><Shift><Alt>Up']"
dconf write /org/gnome/desktop/wm/keybindings/panel-main-menu "['<Alt>F1']"
dconf write /org/gnome/desktop/wm/keybindings/panel-run-dialog "['<Alt>F2']"
dconf write /org/gnome/desktop/wm/keybindings/raise "@as []"
dconf write /org/gnome/desktop/wm/keybindings/raise-or-lower "@as []"
dconf write /org/gnome/desktop/wm/keybindings/set-spew-mark "@as []"
dconf write /org/gnome/desktop/wm/keybindings/show-desktop "['<Primary><Super>d', '<Primary><Alt>d', '<Super>d']"
dconf write /org/gnome/desktop/wm/keybindings/switch-applications "['<Super>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-applications-backward "['<Shift><Super>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-group "['<Super>Above_Tab', '<Alt>Above_Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-group-backward "['<Shift><Super>Above_Tab', '<Shift><Alt>Above_Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-input-source "['<Super>space', 'XF86Keyboard']"
dconf write /org/gnome/desktop/wm/keybindings/switch-input-source-backward "['<Shift><Super>space', '<Shift>XF86Keyboard']"
dconf write /org/gnome/desktop/wm/keybindings/switch-panels "['<Control><Alt>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-panels-backward "['<Shift><Control><Alt>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-1 "['<Super>Home']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-10 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-11 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-12 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-2 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-3 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-4 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-5 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-6 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-7 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-8 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-9 "@as []"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-down "['<Super>Page_Down', '<Control><Alt>Down']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-last "['<Super>End']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-left "['<Control><Alt>Left']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-right "['<Control><Alt>Right']"
dconf write /org/gnome/desktop/wm/keybindings/switch-to-workspace-up "['<Super>Page_Up', '<Control><Alt>Up']"
dconf write /org/gnome/desktop/wm/keybindings/switch-windows "['<Alt>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/switch-windows-backward "['<Shift><Alt>Tab']"
dconf write /org/gnome/desktop/wm/keybindings/toggle-above "@as []"
dconf write /org/gnome/desktop/wm/keybindings/toggle-fullscreen "@as []"
dconf write /org/gnome/desktop/wm/keybindings/toggle-maximized "['<Alt>F10']"
dconf write /org/gnome/desktop/wm/keybindings/toggle-on-all-workspaces "@as []"
dconf write /org/gnome/desktop/wm/keybindings/toggle-shaded "@as []"
dconf write /org/gnome/desktop/wm/keybindings/unmaximize "['<Super>Down', '<Alt>F5']"
dconf write /org/gnome/desktop/wm/preferences/action-double-click-titlebar "'toggle-maximize'"
dconf write /org/gnome/desktop/wm/preferences/action-middle-click-titlebar "'lower'"
dconf write /org/gnome/desktop/wm/preferences/action-right-click-titlebar "'menu'"
dconf write /org/gnome/desktop/wm/preferences/audible-bell "true"
dconf write /org/gnome/desktop/wm/preferences/auto-raise "false"
dconf write /org/gnome/desktop/wm/preferences/auto-raise-delay "500"
dconf write /org/gnome/desktop/wm/preferences/button-layout "':minimize,maximize,close'"
dconf write /org/gnome/desktop/wm/preferences/disable-workarounds "false"
dconf write /org/gnome/desktop/wm/preferences/focus-mode "'click'"
dconf write /org/gnome/desktop/wm/preferences/focus-new-windows "'smart'"
dconf write /org/gnome/desktop/wm/preferences/mouse-button-modifier "'<Super>'"
dconf write /org/gnome/desktop/wm/preferences/num-workspaces "4"
dconf write /org/gnome/desktop/wm/preferences/raise-on-click "true"
dconf write /org/gnome/desktop/wm/preferences/resize-with-right-button "false"
dconf write /org/gnome/desktop/wm/preferences/theme "'Adwaita'"
dconf write /org/gnome/desktop/wm/preferences/titlebar-uses-system-font "false"
dconf write /org/gnome/desktop/wm/preferences/visual-bell "false"
dconf write /org/gnome/desktop/wm/preferences/visual-bell-type "'fullscreen-flash'"
dconf write /org/gnome/desktop/wm/preferences/workspace-names "@as []"
dconf write /org/gnome/mousetweaks/click-type-window-geometry "''"
dconf write /org/gnome/mousetweaks/click-type-window-orientation "'vertical'"
dconf write /org/gnome/mousetweaks/click-type-window-style "'both'"
dconf write /org/gnome/mutter/attach-modal-dialogs "true"
dconf write /org/gnome/mutter/auto-maximize "true"
dconf write /org/gnome/mutter/center-new-windows "false"
dconf write /org/gnome/mutter/check-alive-timeout "uint32 5000"
dconf write /org/gnome/mutter/draggable-border-width "10"
dconf write /org/gnome/mutter/dynamic-workspaces "true"
dconf write /org/gnome/mutter/edge-tiling "true"
dconf write /org/gnome/mutter/experimental-features "@as []"
dconf write /org/gnome/mutter/focus-change-on-pointer-rest "true"
dconf write /org/gnome/mutter/locate-pointer-key "'Control_L'"
dconf write /org/gnome/mutter/no-tab-popup "false"
dconf write /org/gnome/mutter/overlay-key "'Super_L'"
dconf write /org/gnome/mutter/workspaces-only-on-primary "true"
dconf write /org/gnome/mutter/keybindings/rotate-monitor "['XF86RotateWindows']"
dconf write /org/gnome/mutter/keybindings/switch-monitor "['<Super>p', 'XF86Display']"
dconf write /org/gnome/mutter/keybindings/tab-popup-cancel "@as []"
dconf write /org/gnome/mutter/keybindings/tab-popup-select "@as []"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-left "['<Super>Left']"
dconf write /org/gnome/mutter/keybindings/toggle-tiled-right "['<Super>Right']"
dconf write /org/gnome/mutter/wayland/keybindings/restore-shortcuts "['<Super>Escape']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-1 "['<Primary><Alt>F1']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-10 "['<Primary><Alt>F10']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-11 "['<Primary><Alt>F11']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-12 "['<Primary><Alt>F12']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-2 "['<Primary><Alt>F2']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-3 "['<Primary><Alt>F3']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-4 "['<Primary><Alt>F4']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-5 "['<Primary><Alt>F5']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-6 "['<Primary><Alt>F6']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-7 "['<Primary><Alt>F7']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-8 "['<Primary><Alt>F8']"
dconf write /org/gnome/mutter/wayland/keybindings/switch-to-session-9 "['<Primary><Alt>F9']"
dconf write /org/gnome/mutter/x11/fractional-scale-mode "'scale-ui-down'"
dconf write /org/gnome/nautilus/compression/default-compression-format "'zip'"
dconf write /org/gnome/nautilus/icon-view/captions "['none', 'none', 'none']"
dconf write /org/gnome/nautilus/icon-view/default-zoom-level "'small'"
dconf write /org/gnome/nautilus/icon-view/text-ellipsis-limit "['3']"
dconf write /org/gnome/nautilus/list-view/default-column-order "['name', 'size', 'type', 'owner', 'group', 'permissions', 'mime_type', 'where', 'date_modified', 'date_modified_with_time', 'date_accessed', 'recency', 'starred']"
dconf write /org/gnome/nautilus/list-view/default-visible-columns "['name', 'size', 'date_modified', 'starred']"
dconf write /org/gnome/nautilus/list-view/default-zoom-level "'standard'"
dconf write /org/gnome/nautilus/list-view/use-tree-view "false"
dconf write /org/gnome/nautilus/preferences/always-use-location-entry "false"
dconf write /org/gnome/nautilus/preferences/click-policy "'double'"
dconf write /org/gnome/nautilus/preferences/confirm-trash "true"
dconf write /org/gnome/nautilus/preferences/default-folder-viewer "'icon-view'"
dconf write /org/gnome/nautilus/preferences/default-sort-in-reverse-order "false"
dconf write /org/gnome/nautilus/preferences/default-sort-order "'name'"
dconf write /org/gnome/nautilus/preferences/executable-text-activation "'display'"
dconf write /org/gnome/nautilus/preferences/fts-enabled "true"
dconf write /org/gnome/nautilus/preferences/install-mime-activation "true"
dconf write /org/gnome/nautilus/preferences/mouse-back-button "8"
dconf write /org/gnome/nautilus/preferences/mouse-forward-button "9"
dconf write /org/gnome/nautilus/preferences/mouse-use-extra-buttons "true"
dconf write /org/gnome/nautilus/preferences/open-folder-on-dnd-hover "false"
dconf write /org/gnome/nautilus/preferences/recursive-search "'local-only'"
dconf write /org/gnome/nautilus/preferences/search-filter-time-type "'last_modified'"
dconf write /org/gnome/nautilus/preferences/search-view "'list-view'"
dconf write /org/gnome/nautilus/preferences/show-create-link "false"
dconf write /org/gnome/nautilus/preferences/show-delete-permanently "false"
dconf write /org/gnome/nautilus/preferences/show-directory-item-counts "'local-only'"
dconf write /org/gnome/nautilus/preferences/show-hidden-files "false"
dconf write /org/gnome/nautilus/preferences/show-image-thumbnails "'local-only'"
dconf write /org/gnome/nautilus/preferences/tabs-open-position "'after-current-tab'"
dconf write /org/gnome/nautilus/preferences/thumbnail-limit "uint64 10"
dconf write /org/gnome/nautilus/preferences/use-experimental-views "false"
dconf write /org/gnome/nautilus/window-state/initial-size "(890, 550)"
dconf write /org/gnome/nautilus/window-state/maximized "false"
dconf write /org/gnome/nautilus/window-state/sidebar-width "188"
dconf write /org/gnome/nautilus/window-state/start-with-location-bar "true"
dconf write /org/gnome/nautilus/window-state/start-with-sidebar "true"
dconf write /org/gnome/nm-applet/disable-connected-notifications "false"
dconf write /org/gnome/nm-applet/disable-disconnected-notifications "false"
dconf write /org/gnome/nm-applet/disable-vpn-notifications "false"
dconf write /org/gnome/nm-applet/disable-wifi-create "false"
dconf write /org/gnome/nm-applet/show-applet "true"
dconf write /org/gnome/nm-applet/stamp "0"
dconf write /org/gnome/nm-applet/suppress-wireless-networks-available "false"
dconf write /org/gnome/online-accounts/whitelisted-providers "['all']"
dconf write /org/gnome/SessionManager/auto-save-session "false"
dconf write /org/gnome/SessionManager/auto-save-session-one-shot "false"
dconf write /org/gnome/SessionManager/logout-prompt "true"
dconf write /org/gnome/SessionManager/show-fallback-warning "true"
dconf write /org/gnome/settings-daemon/peripherals/active "true"
dconf write /org/gnome/settings-daemon/peripherals/priority "0"
dconf write /org/gnome/settings-daemon/peripherals/keyboard/bell-custom-file "''"
dconf write /org/gnome/settings-daemon/peripherals/keyboard/bell-duration "100"
dconf write /org/gnome/settings-daemon/peripherals/keyboard/bell-mode "'on'"
dconf write /org/gnome/settings-daemon/peripherals/keyboard/bell-pitch "400"
dconf write /org/gnome/settings-daemon/peripherals/keyboard/click "true"
dconf write /org/gnome/settings-daemon/peripherals/keyboard/click-volume "0"
dconf write /org/gnome/settings-daemon/peripherals/mouse/double-click "400"
dconf write /org/gnome/settings-daemon/peripherals/mouse/drag-threshold "8"
dconf write /org/gnome/settings-daemon/peripherals/smartcard/removal-action "'none'"
dconf write /org/gnome/settings-daemon/peripherals/touchscreen/orientation-lock "false"
dconf write /org/gnome/settings-daemon/plugins/a11y-keyboard/active "true"
dconf write /org/gnome/settings-daemon/plugins/a11y-keyboard/priority "0"
dconf write /org/gnome/settings-daemon/plugins/a11y-settings/active "true"
dconf write /org/gnome/settings-daemon/plugins/a11y-settings/priority "0"
dconf write /org/gnome/settings-daemon/plugins/background/active "false"
dconf write /org/gnome/settings-daemon/plugins/background/priority "0"
dconf write /org/gnome/settings-daemon/plugins/color/active "true"
dconf write /org/gnome/settings-daemon/plugins/color/night-light-enabled "false"
dconf write /org/gnome/settings-daemon/plugins/color/night-light-last-coordinates "(91.0, 181.0)"
dconf write /org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic "true"
dconf write /org/gnome/settings-daemon/plugins/color/night-light-schedule-from "20.0"
dconf write /org/gnome/settings-daemon/plugins/color/night-light-schedule-to "6.0"
dconf write /org/gnome/settings-daemon/plugins/color/night-light-temperature "uint32 2700"
dconf write /org/gnome/settings-daemon/plugins/color/priority "0"
dconf write /org/gnome/settings-daemon/plugins/color/recalibrate-display-threshold "uint32 0"
dconf write /org/gnome/settings-daemon/plugins/color/recalibrate-printer-threshold "uint32 0"
dconf write /org/gnome/settings-daemon/plugins/cursor/active "true"
dconf write /org/gnome/settings-daemon/plugins/cursor/priority "0"
dconf write /org/gnome/settings-daemon/plugins/datetime/active "true"
dconf write /org/gnome/settings-daemon/plugins/datetime/priority "0"
dconf write /org/gnome/settings-daemon/plugins/gsdwacom/active "true"
dconf write /org/gnome/settings-daemon/plugins/gsdwacom/priority "0"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/active "true"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/free-percent-notify "0.050000000000000003"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/free-percent-notify-again "0.01"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/free-size-gb-no-notify "1"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/ignore-paths "@as []"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/min-notify-period "10"
dconf write /org/gnome/settings-daemon/plugins/housekeeping/priority "0"
dconf write /org/gnome/settings-daemon/plugins/keyboard/active "true"
dconf write /org/gnome/settings-daemon/plugins/keyboard/priority "0"
dconf write /org/gnome/settings-daemon/plugins/media-keys/active "true"
dconf write /org/gnome/settings-daemon/plugins/media-keys/area-screenshot "['<Shift>Print']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/area-screenshot-clip "['<Ctrl><Shift>Print']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/battery-status "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/battery-status-static "['XF86Battery']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/calculator "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/calculator-static "['XF86Calculator']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/control-center "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/control-center-static "['XF86Tools']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings "@as []"
dconf write /org/gnome/settings-daemon/plugins/media-keys/decrease-text-size "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/eject "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/eject-static "['XF86Eject']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/email "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/email-static "['XF86Mail']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/help "['', '<Super>F1']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/hibernate "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/hibernate-static "['XF86Suspend', 'XF86Hibernate']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/home "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/home-static "['XF86Explorer']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/increase-text-size "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-down "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-down-static "['XF86KbdBrightnessDown']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-toggle "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-toggle-static "['XF86KbdLightOnOff']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-up "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/keyboard-brightness-up-static "['XF86KbdBrightnessUp']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/logout "['<Control><Alt>Delete']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/magnifier "['<Alt><Super>8']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/magnifier-zoom-in "['<Alt><Super>equal']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/magnifier-zoom-out "['<Alt><Super>minus']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/max-screencast-length "uint32 30"
dconf write /org/gnome/settings-daemon/plugins/media-keys/media "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/media-static "['XF86AudioMedia']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/mic-mute "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/mic-mute-static "['XF86AudioMicMute']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/next "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/next-static "['XF86AudioNext', '<Ctrl>XF86AudioNext']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/on-screen-keyboard "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/pause "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/pause-static "['XF86AudioPause']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/play "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/play-static "['XF86AudioPlay', '<Ctrl>XF86AudioPlay']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-forward "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-forward-static "['XF86AudioForward']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-random "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-random-static "['XF86AudioRandomPlay']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-repeat "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-repeat-static "['XF86AudioRepeat']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-rewind "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/playback-rewind-static "['XF86AudioRewind']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/power "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/power-static "['XF86PowerOff']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/previous "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/previous-static "['XF86AudioPrev', '<Ctrl>XF86AudioPrev']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/priority "0"
dconf write /org/gnome/settings-daemon/plugins/media-keys/rfkill "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/rfkill-bluetooth "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/rfkill-bluetooth-static "['XF86Bluetooth']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/rfkill-static "['XF86WLAN', 'XF86UWB', 'XF86RFKill']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static "['<Super>o', 'XF86RotationLockToggle']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-cycle "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-cycle-static "['XF86MonBrightnessCycle']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-down "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-down-static "['XF86MonBrightnessDown']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-up "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-up-static "['XF86MonBrightnessUp']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screencast "['<Ctrl><Shift><Alt>R']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screenreader "['<Alt><Super>s']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screensaver "['<Super>l']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screensaver-static "['XF86ScreenSaver']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screenshot "['Print']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/screenshot-clip "['<Ctrl>Print']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/search "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/search-static "['XF86Search']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/stop "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/stop-static "['XF86AudioStop']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/suspend "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/suspend-static "['XF86Sleep']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/terminal "['<Primary><Alt>t']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/toggle-contrast "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/touchpad-off "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/touchpad-off-static "['XF86TouchpadOff']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/touchpad-on "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/touchpad-on-static "['XF86TouchpadOn']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/touchpad-toggle "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/touchpad-toggle-static "['XF86TouchpadToggle', '<Ctrl><Super>XF86TouchpadToggle']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-down "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-down-precise "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-down-precise-static "['<Shift>XF86AudioLowerVolume', '<Ctrl><Shift>XF86AudioLowerVolume']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-down-quiet "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-down-quiet-static "['<Alt>XF86AudioLowerVolume', '<Alt><Ctrl>XF86AudioLowerVolume']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-down-static "['XF86AudioLowerVolume', '<Ctrl>XF86AudioLowerVolume']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-mute "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-mute-quiet "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-mute-quiet-static "['<Alt>XF86AudioMute']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-mute-static "['XF86AudioMute']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-step "6"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-up "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-up-precise "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-up-precise-static "['<Shift>XF86AudioRaiseVolume', '<Ctrl><Shift>XF86AudioRaiseVolume']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-up-quiet "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-up-quiet-static "['<Alt>XF86AudioRaiseVolume', '<Alt><Ctrl>XF86AudioRaiseVolume']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/volume-up-static "['XF86AudioRaiseVolume', '<Ctrl>XF86AudioRaiseVolume']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/window-screenshot "['<Alt>Print']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/window-screenshot-clip "['<Ctrl><Alt>Print']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/www "['']"
dconf write /org/gnome/settings-daemon/plugins/media-keys/www-static "['XF86WWW']"
dconf write /org/gnome/settings-daemon/plugins/mouse/active "true"
dconf write /org/gnome/settings-daemon/plugins/mouse/priority "0"
dconf write /org/gnome/settings-daemon/plugins/orientation/active "true"
dconf write /org/gnome/settings-daemon/plugins/orientation/priority "0"
dconf write /org/gnome/settings-daemon/plugins/power/active "true"
dconf write /org/gnome/settings-daemon/plugins/power/ambient-enabled "true"
dconf write /org/gnome/settings-daemon/plugins/power/button-hibernate "'hibernate'"
dconf write /org/gnome/settings-daemon/plugins/power/button-power "'interactive'"
dconf write /org/gnome/settings-daemon/plugins/power/button-sleep "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/button-suspend "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/critical-battery-action "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/idle-brightness "30"
dconf write /org/gnome/settings-daemon/plugins/power/idle-dim "true"
dconf write /org/gnome/settings-daemon/plugins/power/lid-close-ac-action "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/lid-close-battery-action "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/lid-close-suspend-with-external-monitor "false"
dconf write /org/gnome/settings-daemon/plugins/power/notify-perhaps-recall "true"
dconf write /org/gnome/settings-daemon/plugins/power/percentage-action "2"
dconf write /org/gnome/settings-daemon/plugins/power/percentage-critical "3"
dconf write /org/gnome/settings-daemon/plugins/power/percentage-low "10"
dconf write /org/gnome/settings-daemon/plugins/power/power-button-action "'interactive'"
dconf write /org/gnome/settings-daemon/plugins/power/priority "0"
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-timeout "3600"
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type "'nothing'"
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-timeout "1200"
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type "'suspend'"
dconf write /org/gnome/settings-daemon/plugins/power/time-action "120"
dconf write /org/gnome/settings-daemon/plugins/power/time-critical "300"
dconf write /org/gnome/settings-daemon/plugins/power/time-low "1200"
dconf write /org/gnome/settings-daemon/plugins/power/use-time-for-policy "true"
dconf write /org/gnome/settings-daemon/plugins/print-notifications/active "false"
dconf write /org/gnome/settings-daemon/plugins/print-notifications/priority "0"
dconf write /org/gnome/settings-daemon/plugins/remote-display/active "true"
dconf write /org/gnome/settings-daemon/plugins/remote-display/priority "0"
dconf write /org/gnome/settings-daemon/plugins/rfkill/active "true"
dconf write /org/gnome/settings-daemon/plugins/rfkill/priority "0"
dconf write /org/gnome/settings-daemon/plugins/screensaver-proxy/active "true"
dconf write /org/gnome/settings-daemon/plugins/screensaver-proxy/priority "0"
dconf write /org/gnome/settings-daemon/plugins/sharing/active "true"
dconf write /org/gnome/settings-daemon/plugins/sharing/priority "0"
dconf write /org/gnome/settings-daemon/plugins/smartcard/active "true"
dconf write /org/gnome/settings-daemon/plugins/smartcard/priority "0"
dconf write /org/gnome/settings-daemon/plugins/sound/active "true"
dconf write /org/gnome/settings-daemon/plugins/sound/priority "0"
dconf write /org/gnome/settings-daemon/plugins/wwan/unlock-sim "false"
dconf write /org/gnome/settings-daemon/plugins/xrandr/active "true"
dconf write /org/gnome/settings-daemon/plugins/xrandr/default-configuration-file "'/etc/gnome-settings-daemon/xrandr/monitors.xml'"
dconf write /org/gnome/settings-daemon/plugins/xrandr/default-monitors-setup "'follow-lid'"
dconf write /org/gnome/settings-daemon/plugins/xrandr/priority "0"
dconf write /org/gnome/settings-daemon/plugins/xsettings/active "true"
dconf write /org/gnome/settings-daemon/plugins/xsettings/antialiasing "'rgba'"
dconf write /org/gnome/settings-daemon/plugins/xsettings/disabled-gtk-modules "@as []"
dconf write /org/gnome/settings-daemon/plugins/xsettings/enabled-gtk-modules "@as []"
dconf write /org/gnome/settings-daemon/plugins/xsettings/hinting "'slight'"
dconf write /org/gnome/settings-daemon/plugins/xsettings/overrides "@a{sv} {}"
dconf write /org/gnome/settings-daemon/plugins/xsettings/priority "0"
dconf write /org/gnome/settings-daemon/plugins/xsettings/rgba-order "'rgb'"
dconf write /org/gnome/shell/always-show-log-out "true"
dconf write /org/gnome/shell/app-picker-layout "@aa{sv} []"
dconf write /org/gnome/shell/app-picker-view "uint32 0"
dconf write /org/gnome/shell/command-history "@as []"
dconf write /org/gnome/shell/development-tools "true"
dconf write /org/gnome/shell/had-bluetooth-devices-setup "false"
dconf write /org/gnome/shell/introspect "false"
dconf write /org/gnome/shell/looking-glass-history "@as []"
dconf write /org/gnome/shell/remember-mount-password "false"
dconf write /org/gnome/shell/app-switcher/current-workspace-only "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/activate-single-window "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/animate-show-apps "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/animation-time "0.20000000000000001"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-1 "['<Ctrl><Super>1']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-10 "['<Ctrl><Super>0']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-2 "['<Ctrl><Super>2']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-3 "['<Ctrl><Super>3']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-4 "['<Ctrl><Super>4']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-5 "['<Ctrl><Super>5']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-6 "['<Ctrl><Super>6']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-7 "['<Ctrl><Super>7']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-8 "['<Ctrl><Super>8']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-ctrl-hotkey-9 "['<Ctrl><Super>9']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-1 "['<Super>1']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-10 "['<Super>0']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-2 "['<Super>2']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-3 "['<Super>3']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-4 "['<Super>4']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-5 "['<Super>5']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-6 "['<Super>6']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-7 "['<Super>7']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-8 "['<Super>8']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-hotkey-9 "['<Super>9']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-1 "['<Shift><Super>1']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-10 "['<Shift><Super>0']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-2 "['<Shift><Super>2']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-3 "['<Shift><Super>3']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-4 "['<Shift><Super>4']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-5 "['<Shift><Super>5']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-6 "['<Shift><Super>6']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-7 "['<Shift><Super>7']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-8 "['<Shift><Super>8']"
dconf write /org/gnome/shell/extensions/dash-to-dock/app-shift-hotkey-9 "['<Shift><Super>9']"
dconf write /org/gnome/shell/extensions/dash-to-dock/apply-custom-theme "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/apply-glossy-effect "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/autohide "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/autohide-in-fullscreen "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/background-color "'#ffffff'"
dconf write /org/gnome/shell/extensions/dash-to-dock/background-opacity "0.69999999999999996"
dconf write /org/gnome/shell/extensions/dash-to-dock/bolt-support "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/click-action "'focus-or-previews'"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-background-color "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-customize-running-dots "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-border-color "'#e95420'"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-border-width "0"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-color "'#e95420'"
dconf write /org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/customize-alphas "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size "48"
dconf write /org/gnome/shell/extensions/dash-to-dock/dock-fixed "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/dock-position "'LEFT'"
dconf write /org/gnome/shell/extensions/dash-to-dock/extend-height "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/force-straight-corner "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/height-fraction "0.90000000000000002"
dconf write /org/gnome/shell/extensions/dash-to-dock/hide-delay "0.20000000000000001"
dconf write /org/gnome/shell/extensions/dash-to-dock/hot-keys "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/hotkeys-overlay "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/hotkeys-show-dock "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/icon-size-fixed "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/intellihide "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/intellihide-mode "'ALL_WINDOWS'"
dconf write /org/gnome/shell/extensions/dash-to-dock/isolate-monitors "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/isolate-workspaces "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/max-alpha "0.80000000000000004"
dconf write /org/gnome/shell/extensions/dash-to-dock/middle-click-action "'launch'"
dconf write /org/gnome/shell/extensions/dash-to-dock/min-alpha "0.20000000000000001"
dconf write /org/gnome/shell/extensions/dash-to-dock/minimize-shift "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/multi-monitor "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/preferred-monitor "0"
dconf write /org/gnome/shell/extensions/dash-to-dock/pressure-threshold "100.0"
dconf write /org/gnome/shell/extensions/dash-to-dock/require-pressure-to-show "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/running-indicator-dominant-color "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/running-indicator-style "'DOTS'"
dconf write /org/gnome/shell/extensions/dash-to-dock/scroll-action "'switch-workspace'"
dconf write /org/gnome/shell/extensions/dash-to-dock/scroll-switch-workspace "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/shift-click-action "'launch'"
dconf write /org/gnome/shell/extensions/dash-to-dock/shift-middle-click-action "'minimize'"
dconf write /org/gnome/shell/extensions/dash-to-dock/shortcut "['<Super>q']"
dconf write /org/gnome/shell/extensions/dash-to-dock/shortcut-text "'<Super>q'"
dconf write /org/gnome/shell/extensions/dash-to-dock/shortcut-timeout "2.0"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-apps-at-top "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-delay "0.25"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-favorites "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-mounts "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-running "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-show-apps-button "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-trash "false"
dconf write /org/gnome/shell/extensions/dash-to-dock/show-windows-preview "true"
dconf write /org/gnome/shell/extensions/dash-to-dock/transparency-mode "'FIXED'"
dconf write /org/gnome/shell/extensions/dash-to-dock/unity-backlit-items "false"
dconf write /org/gnome/shell/extensions/ding/add-volumes-opposite "true"
dconf write /org/gnome/shell/extensions/ding/icon-size "'standard'"
dconf write /org/gnome/shell/extensions/ding/show-drop-place "true"
dconf write /org/gnome/shell/extensions/ding/show-home "true"
dconf write /org/gnome/shell/extensions/ding/show-network-volumes "false"
dconf write /org/gnome/shell/extensions/ding/show-trash "true"
dconf write /org/gnome/shell/extensions/ding/show-volumes "true"
dconf write /org/gnome/shell/extensions/ding/start-corner "'top-left'"
dconf write /org/gnome/shell/keybindings/focus-active-notification "['<Super>n']"
dconf write /org/gnome/shell/keybindings/open-application-menu "['<Super>F10']"
dconf write /org/gnome/shell/keybindings/switch-to-application-1 "['<Super>1']"
dconf write /org/gnome/shell/keybindings/switch-to-application-2 "['<Super>2']"
dconf write /org/gnome/shell/keybindings/switch-to-application-3 "['<Super>3']"
dconf write /org/gnome/shell/keybindings/switch-to-application-4 "['<Super>4']"
dconf write /org/gnome/shell/keybindings/switch-to-application-5 "['<Super>5']"
dconf write /org/gnome/shell/keybindings/switch-to-application-6 "['<Super>6']"
dconf write /org/gnome/shell/keybindings/switch-to-application-7 "['<Super>7']"
dconf write /org/gnome/shell/keybindings/switch-to-application-8 "['<Super>8']"
dconf write /org/gnome/shell/keybindings/switch-to-application-9 "['<Super>9']"
dconf write /org/gnome/shell/keybindings/toggle-application-view "['<Super>a']"
dconf write /org/gnome/shell/keybindings/toggle-message-tray "['<Super>v', '<Super>m']"
dconf write /org/gnome/shell/keybindings/toggle-overview "['<Super>s']"
dconf write /org/gnome/shell/overrides/attach-modal-dialogs "true"
dconf write /org/gnome/shell/overrides/dynamic-workspaces "true"
dconf write /org/gnome/shell/overrides/edge-tiling "true"
dconf write /org/gnome/shell/overrides/focus-change-on-pointer-rest "true"
dconf write /org/gnome/shell/overrides/workspaces-only-on-primary "true"
dconf write /org/gnome/shell/weather/automatic-location "false"
dconf write /org/gnome/shell/weather/locations "@av []"
dconf write /org/gnome/shell/window-switcher/app-icon-mode "'both'"
dconf write /org/gnome/shell/window-switcher/current-workspace-only "true"
dconf write /org/gnome/shell/world-clocks/locations "@av []"
dconf write /org/gnome/system/locale/region "''"
dconf write /org/gnome/system/location/enabled "false"
dconf write /org/gnome/system/location/max-accuracy-level "'exact'"
dconf write /org/gnome/system/proxy/http/authentication-password "''"
dconf write /org/gnome/system/proxy/http/authentication-user "''"
dconf write /org/gnome/system/proxy/http/enabled "false"
dconf write /org/gnome/system/proxy/http/host "''"
dconf write /org/gnome/system/proxy/http/port "8080"
dconf write /org/gnome/system/proxy/http/use-authentication "false"
dconf write /org/gnome/system/proxy/https/host "''"
dconf write /org/gnome/system/proxy/https/port "0"
dconf write /org/gnome/Terminal/Legacy/Keybindings/close-tab "'<Ctrl><Shift>w'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/close-window "'<Ctrl><Shift>q'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/copy "'<Ctrl><Shift>c'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/copy-html "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/detach-tab "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/export "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/find "'<Control><Shift>F'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/find-clear "'<Control><Shift>J'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/find-next "'<Control><Shift>G'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/find-previous "'<Control><Shift>H'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/full-screen "'F11'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/header-menu "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/help "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/move-tab-left "'<Ctrl><Shift>Page_Up'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/move-tab-right "'<Ctrl><Shift>Page_Down'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/new-tab "'<Ctrl><Shift>t'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/new-window "'<Ctrl><Shift>n'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/next-tab "'<Control>Page_Down'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/paste "'<Ctrl><Shift>v'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/preferences "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/prev-tab "'<Control>Page_Up'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/print "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/read-only "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/reset "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/reset-and-clear "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/save-contents "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/select-all "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-1 "'<Alt>1'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-10 "'<Alt>0'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-11 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-12 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-13 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-14 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-15 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-16 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-17 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-18 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-19 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-2 "'<Alt>2'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-20 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-21 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-22 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-23 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-24 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-25 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-26 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-27 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-28 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-29 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-3 "'<Alt>3'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-30 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-31 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-32 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-33 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-34 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-35 "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-4 "'<Alt>4'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-5 "'<Alt>5'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-6 "'<Alt>6'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-7 "'<Alt>7'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-8 "'<Alt>8'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-9 "'<Alt>9'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/switch-to-tab-last "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/toggle-menubar "'disabled'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/zoom-in "'<Ctrl>plus'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/zoom-normal "'<Ctrl>0'"
dconf write /org/gnome/Terminal/Legacy/Keybindings/zoom-out "'<Ctrl>minus'"
dconf write /org/gnome/Terminal/Legacy/Settings/confirm-close "true"
dconf write /org/gnome/Terminal/Legacy/Settings/default-show-menubar "true"
dconf write /org/gnome/Terminal/Legacy/Settings/headerbar "@mb nothing"
dconf write /org/gnome/Terminal/Legacy/Settings/menu-accelerator-enabled "true"
dconf write /org/gnome/Terminal/Legacy/Settings/mnemonics-enabled "false"
dconf write /org/gnome/Terminal/Legacy/Settings/new-tab-position "'last'"
dconf write /org/gnome/Terminal/Legacy/Settings/new-terminal-mode "'window'"
dconf write /org/gnome/Terminal/Legacy/Settings/schema-version "uint32 3"
dconf write /org/gnome/Terminal/Legacy/Settings/shell-integration-enabled "true"
dconf write /org/gnome/Terminal/Legacy/Settings/shortcuts-enabled "true"
dconf write /org/gnome/Terminal/Legacy/Settings/tab-policy "'automatic'"
dconf write /org/gnome/Terminal/Legacy/Settings/tab-position "'top'"
dconf write /org/gnome/Terminal/Legacy/Settings/theme-variant "'dark'"
dconf write /org/gnome/Terminal/Legacy/Settings/unified-menu "false"
