# Based on the Dockerfile by Emanuele Palazzetti <emanuele.palazzetti@gmail.com>
# https://github.com/palazzem/archlinux-toolbox

FROM docker.io/archlinux:latest

ENV NAME=arch-toolbox VERSION=rolling
LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating Arch toolbox containers" \
      maintainer="Adam Israel <adam@adamisrael.com>"

# Install required dependencies to run `toolbox`
RUN pacman -Sy sudo git --noconfirm && \
  pacman -Scc --noconfirm

# COPY extra-packages /
# RUN sed -Ei '/apt-get (update|upgrade)/s/^/#/' /usr/local/sbin/unminimize && \
#     apt-get update && \
#     yes | /usr/local/sbin/unminimize && \
#     DEBIAN_FRONTEND=noninteractive apt-get -y install \
#         ubuntu-minimal ubuntu-standard \
#         libnss-myhostname \
#         $(cat extra-packages | xargs) && \
#     rm -rd /var/lib/apt/lists/*
# RUN rm /extra-packages


# Required steps otherwise `toolbox` fails to start the container:
# 1. machine-id must be present in the base image
# 2. $(whoami) must be in the sudoer list without password
# 3. /media must be present (toolbox tries to remove the folder and create a symlink)
RUN touch /etc/machine-id && \
  echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox && \
  mkdir /media

CMD /bin/bash