#!/bin/bash
# Install tailscale

set -u

if [ ! -e /etc/yum.repos.d/1password.repo ]; then
    echo "Installing repo..."
    sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://downloads.1password.com/linux/keys/1password.asc" > /etc/yum.repos.d/1password.repo'
fi

# Check if 1password is already installed
rpm -q 1password > /dev/null
if [ $? -eq 1 ]; then
    echo "Installing 1password package..."
    rpm-ostree install 1password
    echo "Please reboot to finish installation of the layered package and re-run this script to enable tailscale."
    exit 0
fi
