#!/bin/bash
# This for sure doesn't work, just dumping stuff in here while I reorganize

BITS=./bits
source $BITS/common

# Enable beta repo
flatpak_install_remote flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak_install flathub-beta applications-beta.list

# Adjust flatpak permissions so PWAs work on chromium-based browsers
flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.brave.Browser
flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.google.Chrome
flatpak override --user --filesystem=~/.local/share/applications --filesystem=~/.local/share/icons com.microsoft.Edge