#!/bin/bash
# Install tailscale

set -u

if [ ! -e /etc/yum.repos.d/tailscale.repo ]; then
    echo "Installing repo..."
    sudo curl -s https://pkgs.tailscale.com/stable/fedora/tailscale.repo -o /etc/yum.repos.d/tailscale.repo > /dev/null
    # Disable repo_gpgcheck, which doesn't work on Silverblue 36+
    sudo sed -i 's/repo_gpgcheck=1/repo_gpgcheck=0/' /etc/yum.repos.d/tailscale.repo
fi

# Check if tailscale is already installed
rpm -q tailscale > /dev/null
if [ $? -eq 1 ]; then
    echo "Installing tailscale package..."
    rpm-ostree install tailscale
    echo "Please reboot to finish installation of the layered package and re-run this script to enable tailscale."
    exit 0
fi

echo "Enabling tailscale (systemd)..."
sudo systemctl enable --now tailscaled > /dev/null

echo "Starting tailscale..."
sudo tailscale up
